---
- hosts: clusternodes
  remote_user: pi
  become: true
  tasks:
    - name: Check that the somefile.conf exists
      stat:
        path: /etc/docker
      register: stat_result

    - name: install docker
      script: install_docker.sh
      when: stat_result.stat.exists == False

    - group: 
        name: docker
        state: present
      notify: 
      - restart docker

    - user: 
        name: pi
        groups: docker
        append: yes
      notify: 
      - restart docker

    - name: Create docker service directory
      file: 
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: "u=rw,g=r,o=r"

    - template:
        src: overlay.conf
        dest: /etc/systemd/system/docker.service.d/overlay.conf
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      notify:
      - restart docker

#    - debug:
#        msg: "FORCING restart of docker for testing"
#      changed_when: true
#      notify:
#      - restart docker

  handlers:
    - name: restart docker
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker
